"""
Django settings for onma_bot project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-*=2(o)5l4-d_g6$edkul0r1^1re4waz-tf#-u-*fdnzu97j^#4'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    # 'bot' must come before 'django.contrib.admin' so its
    # templates/admin/base_site.html override (branding) is found first —
    # Django's app_directories template loader returns the first match in
    # INSTALLED_APPS order.
    'bot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves static files directly from the WSGI app (compressed + far-future
    # cache headers) — no separate Nginx/IIS static-file config needed.
    # Perfectly safe in dev too: falls through to Django's normal static
    # handling in effect, just adds nothing when DEBUG serves via runserver.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Dev default: allow any origin so the widget can be tested from the XAMPP
# site (a different port = a different origin) without extra config. Lock
# this down to the real site origin(s) before going anywhere near production
# — see the V2 build guide's Security checklist ("CORS locked to the site's
# own origin(s)").
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()
]

# Production-hardening switches, off by default so local HTTP dev keeps
# working — flip these via env vars when deploying behind real TLS. Run
# `python manage.py check --deploy` before going live; it covers most of
# Django's own deployment checklist (SECRET_KEY strength, DEBUG, etc.) beyond
# what's set explicitly here. `bot/checks.py` adds one more check specific to
# CORS_ALLOW_ALL_ORIGINS, which Django's own checks don't know about.
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Trusts the reverse proxy's X-Forwarded-Proto header to know a request was
# HTTPS even though it reaches Gunicorn/Waitress as plain HTTP internally.
# Safe ONLY because deploy/run_gunicorn.sh and deploy/run_waitress.bat both
# bind to 127.0.0.1 — the app is never directly reachable bypassing the
# proxy, so nothing else can forge this header. Without this,
# SECURE_SSL_REDIRECT=True causes an infinite redirect loop in production
# (Django keeps thinking the request is still HTTP).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'onma_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onma_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# SQLite by default (zero setup, fine for this foundation's traffic/data
# size). Set DATABASE_ENGINE=postgresql in .env to switch — SQLite doesn't
# handle concurrent writes well under a real multi-worker WSGI server and
# has no replication story, so production should move to Postgres. Nothing
# else in the app depends on which one is active; switching is just this
# block + `pip install "psycopg[binary]"` (already in requirements.txt) +
# `manage.py migrate` on the new database (re-seed/re-crawl the data rather
# than migrating rows — it's small).

if os.environ.get('DATABASE_ENGINE', 'sqlite3') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'onma_chatbot'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            # Reuses connections across requests instead of reconnecting each
            # time — meaningful under a real WSGI server with sustained
            # traffic; harmless at dev traffic levels too.
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
#
# `runserver` serves static files itself in dev and ignores STATIC_ROOT
# entirely — it only matters once a real WSGI server is in front (Waitress/
# Gunicorn don't serve static files at all on their own). Run
# `manage.py collectstatic` once as part of deployment to populate it;
# WhiteNoise (see MIDDLEWARE) then serves everything from there with
# compression and cache headers, so no separate Nginx/IIS static config,
# S3 bucket, or CDN is required for a project this size.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Overriding STORAGES at all means Django no longer fills in its own
    # 'default' (regular FileField/ImageField uploads, e.g. BotSettings.bot_icon)
    # — `manage.py check` doesn't catch a missing key here, it only surfaces
    # as InvalidStorageError the first time a file is actually saved.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Admin uploads (currently just BotSettings.bot_icon). WhiteNoise only covers
# STATIC_ROOT (collectstatic'd app assets), not admin-uploaded MEDIA_ROOT
# files, so these are served by a plain Django view registered in
# onma_bot/urls.py — adequate for a handful of small icon files; revisit
# with real object storage (S3, etc.) if uploads ever need to scale further.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Dev default prints emails to the console instead of sending them. Set real
# SMTP_* env vars (and EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend)
# before this needs to actually deliver mail.

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@onmascout.local')
SALES_NOTIFICATION_EMAIL = os.environ.get('SALES_NOTIFICATION_EMAIL', 'sales@onmascout.local')


# ONMA scout chatbot settings — same shape as V1's config.php.

LLM_PROVIDER = os.environ.get('LLM_PROVIDER', 'openai')
LLM_MODEL = os.environ.get('LLM_MODEL', 'gpt-4o-mini')
LLM_ENDPOINT = os.environ.get('LLM_ENDPOINT', 'https://api.openai.com/v1/chat/completions')
LLM_API_KEY = os.environ.get('LLM_API_KEY', '')

CHAT_MAX_MESSAGE_LENGTH = int(os.environ.get('CHAT_MAX_MESSAGE_LENGTH', '1000'))
CHAT_RATE_LIMIT_PER_MINUTE = int(os.environ.get('CHAT_RATE_LIMIT_PER_MINUTE', '12'))

# RAG: real embeddings + cosine-similarity retrieval over KnowledgeChunk rows
# (see bot/retrieval.py). Same OpenAI account/key as LLM_API_KEY above.
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL', 'text-embedding-3-small')
EMBEDDING_ENDPOINT = os.environ.get('EMBEDDING_ENDPOINT', 'https://api.openai.com/v1/embeddings')
RAG_TOP_K = int(os.environ.get('RAG_TOP_K', '4'))
RAG_SIMILARITY_THRESHOLD = float(os.environ.get('RAG_SIMILARITY_THRESHOLD', '0.15'))

# GDPR: how long a chat session (and its messages) may be kept before
# `manage.py purge_old_data` considers it eligible for deletion. Leads are
# NOT covered by this — they're a separate business record with their own
# consent/retention basis, purging chat history doesn't touch them.
RETENTION_DAYS = int(os.environ.get('RETENTION_DAYS', '90'))

# Answer caching (bot/answer_cache.py): skip embedding + LLM calls on a
# repeated question, keyed on (language, normalized question) shared across
# all sessions. Set ANSWER_CACHE_ENABLED=False to disable outright.
ANSWER_CACHE_ENABLED = os.environ.get('ANSWER_CACHE_ENABLED', 'True') == 'True'
ANSWER_CACHE_TTL_SECONDS = int(os.environ.get('ANSWER_CACHE_TTL_SECONDS', str(24 * 3600)))

# Cloudflare Turnstile (bot/turnstile.py): bot protection on the public chat
# endpoints. Blank keys = disabled (default, so local dev needs no Cloudflare
# account). Sign up at https://dash.cloudflare.com/?to=/:account/turnstile
# for real keys, or use Cloudflare's published test keys during development:
#   site key  1x00000000000000000000BB / secret 1x0000000000000000000000000000000AA -> always passes
#   site key  2x00000000000000000000BB / secret 2x0000000000000000000000000000000AA -> always blocks
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')
TURNSTILE_ENABLED = bool(TURNSTILE_SITE_KEY and TURNSTILE_SECRET_KEY)
TURNSTILE_FAIL_OPEN = os.environ.get('TURNSTILE_FAIL_OPEN', 'True') == 'True'
