# Generated by Django 6.1.1 on 2026-09-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='retrievable',
            field=models.BooleanField(default=True, help_text="Include this entry's content in vector-search retrieval. Turn off for meta/behavior-rule entries that should not compete for relevance against a visitor's question — those belong in code as always-on instructions instead."),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=5)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bot.knowledgeentry')),
            ],
            options={
                'ordering': ['entry__order', 'id'],
            },
        ),
    ]
