# Generated by Django 6.1.1 on 2026-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_knowledgeentry_retrievable_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='lead_prompted',
            field=models.BooleanField(default=False, help_text='Whether the lead-capture form has already been offered in this session (shown at most once).'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_at',
            field=models.DateTimeField(blank=True, help_text="When the visitor ticked the lead form's own consent checkbox (separate from cookie consent).", null=True),
        ),
    ]
