# Generated by Django 6.1.1 on 2026-09-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_chatsession_lead_prompted_lead_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='category',
            field=models.CharField(blank=True, help_text='Optional grouping (e.g. SEO/SEA/Webdesign). Set automatically by the crawler when detectable.', max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 of the crawled content, used to detect real changes on re-crawl.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='source_url',
            field=models.URLField(blank=True, help_text='Set automatically by manage.py crawl_site. Blank for hand-typed entries.', max_length=500, null=True, unique=True),
        ),
    ]
