# Generated by Django 6.1.1 on 2026-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_knowledgeentry_category_knowledgeentry_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='detected_language',
            field=models.CharField(blank=True, help_text="Auto-detected from this message's text (user messages only). Blank for assistant replies.", max_length=5),
        ),
    ]
