# Generated by Django 6.1.1 on 2026-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chatmessage_detected_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=5)),
                ('question_text', models.TextField(blank=True, help_text='Normalized question, kept for admin visibility.')),
                ('answer', models.TextField()),
                ('sources_json', models.JSONField(blank=True, null=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-hit_count', '-created_at'],
            },
        ),
    ]
