# Generated by Django 6.1.1 on 2026-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_answercache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(blank=True, help_text='Overrides the widget header title (e.g. "ONMA scout Assistant"). Blank = widget\'s own per-language default.', max_length=100)),
                ('bot_icon', models.ImageField(blank=True, help_text='Overrides the default ONMA logo avatar shown for bot messages. Blank = the bundled onma.png.', null=True, upload_to='bot_settings/')),
                ('llm_api_key', models.CharField(blank=True, help_text='Overrides LLM_API_KEY from .env.', max_length=255)),
                ('llm_model', models.CharField(blank=True, help_text='e.g. gpt-4o-mini, or openai/gpt-4o-mini for OpenRouter. Overrides LLM_MODEL.', max_length=100)),
                ('llm_endpoint', models.URLField(blank=True, help_text='Overrides LLM_ENDPOINT.', max_length=300)),
                ('embedding_model', models.CharField(blank=True, help_text='Overrides EMBEDDING_MODEL.', max_length=100)),
                ('embedding_endpoint', models.URLField(blank=True, help_text='Overrides EMBEDDING_ENDPOINT.', max_length=300)),
                ('sales_notification_email', models.EmailField(blank=True, help_text='Where lead notifications are sent. Overrides SALES_NOTIFICATION_EMAIL.', max_length=254)),
                ('smtp_host', models.CharField(blank=True, help_text='Overrides EMAIL_HOST.', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, help_text='Overrides EMAIL_PORT.', null=True)),
                ('smtp_user', models.CharField(blank=True, help_text='Overrides EMAIL_HOST_USER.', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='Overrides EMAIL_HOST_PASSWORD.', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Overrides EMAIL_USE_TLS — only applies if an SMTP host is set above.')),
                ('default_from_email', models.EmailField(blank=True, help_text='Overrides DEFAULT_FROM_EMAIL.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot settings',
                'verbose_name_plural': 'Bot settings',
            },
        ),
    ]
